project:
  type: website
  output-dir: docs

website:
  title: "Maina Handmaker"
  favicon: images/favicon.png
  navbar:
    title: Maina Handmaker
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - media.qmd
      - publications.qmd

format:
  html:
    theme:
    - simplex
    - custom.scss
    mainfont: Figtree
    css: styles.css
    toc: true

editor: visual

